Repository libero/article-store, pull requests merged in 2019-11, with the labels that each got.

#3 Add empty HTTP server
  .docker/docker-compose.dev.yml
  .docker/docker-compose.yml
  .dockerignore
  .gitignore
  .travis/smoke-test.sh
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/app.ts
  src/index.ts
  tsconfig.json
Labels: ✨ Features

#4 Add code linting
  .docker/docker-compose.dev.yml
  .eslintignore
  .eslintrc.js
  .travis.yml
  Dockerfile
  Makefile
  package-lock.json
  package.json
Labels: :gear: CI

#5 Restart the dev container on code changes
  package-lock.json
  package.json
Labels: :hammer: Build

#8 Fix TypeScript file inclusion
  tsconfig.json
Labels: :beetle: Bug Fix

#6 Add test suite
  .docker/docker-compose.dev.yml
  .eslintrc.js
  .travis.yml
  Dockerfile
  Makefile
  jest.config.js
  package-lock.json
  package.json
  test/index.test.ts
Labels: :gear: CI

#9 Add a router
  package-lock.json
  package.json
  src/app.ts
  src/router.ts
  src/routes/index.ts
  test/app.test.ts
  test/index.test.ts
  test/router.test.ts
Labels: :new: Feature

#10 Add entry point
  .travis/smoke-test.sh
  README.md
  package-lock.json
  package.json
  src/router.ts
  src/routes/entry-point.ts
  test/middleware.ts
  test/routes/context.ts
  test/routes/entry-point.test.ts
Labels: :new: Feature

#11 Support cross-origin requests
  package-lock.json
  package.json
  src/app.ts
  test/app.test.ts
Labels: :new: Feature

#12 Use JSON-LD context to make URIs absolute
  src/routes/entry-point.ts
Labels: :package: Refactor

#13 Use dummy router in middleware tests
  test/routes/context.ts
  test/routes/entry-point.test.ts
Labels: :package: Refactor

#15 Follow official Node.js Docker image best practices
  Dockerfile
Labels: :hammer: Build

#17 Make sure eslint uses TypeScript definitions
  .eslintrc.js
  package-lock.json
  package.json
Labels: :recycle: Chore

#18 Throw a Not Found error
  package-lock.json
  package.json
  src/app.ts
  src/middleware/routing.ts
  test/context.ts
  test/middleware/routing.test.ts
  test/routes/entry-point.test.ts
Labels: :new: Feature

#20 Remove empty URL parameters
  package-lock.json
  package.json
  src/routes/entry-point.ts
Labels: :gem: Style

#14 Add Hydra API Documentation
  package-lock.json
  package.json
  src/app.ts
  src/middleware/api-documentation.ts
  src/router.ts
  src/routes/api-documentation.ts
  src/routes/index.ts
  test/app.test.ts
  test/routes/api-documentation.test.ts
Labels: :new: Feature

#19 Return errors in Hydra format
  src/app.ts
  src/middleware/error-handler.ts
  test/context.ts
  test/middleware.ts
  test/middleware/error-handler.test.ts
Labels: :new: Feature

#23 Add type definitions for format-link-header
  package-lock.json
  package.json
Labels: :recycle: Chore

#21 Add Hydra console
  .docker/docker-compose.yml
  README.md
Labels: :new: Feature

#24 Add API documentation middleware test
  test/middleware/api-documentation.test.ts
Labels: :rotating_light: Tests

#26 chore: Fixed NPM Advisory for Handlebars dependency
  package-lock.json
Labels: :hammer: Build

#28 Added type for unknown error, based on input of http-errors library
  package-lock.json
  package.json
  src/middleware/error-handler.ts
  test/context.ts
  test/middleware/error-handler.test.ts
Labels: :package: Refactor

#27 Populated generics with RouterContext
  src/middleware/routing.ts
  test/middleware.ts
Labels: :package: Refactor

#30 Configure Dependabot
  .dependabot/config.yml
  .dockerignore
Labels: :hammer: Build

#34 Install libero/scripts locally
  Makefile
Labels: :hammer: Build

#44 Allow running an arbitrary command on the app container
  Makefile
Labels: :recycle: Chore

#33 Add Hydra validator to CI
  .travis.yml
  .travis/analyse.sh
  package-lock.json
  package.json
Labels: :gear: CI

#46 Fix node identifiers in the collection manages block
  src/routes/article-list.ts
Labels: :beetle: Bug Fix

#56 Allow Dependabot to auto-merge non-major updates
  .dependabot/config.yml
Labels: :hammer: Build

#61 Only build the master branch
  .travis.yml
Labels: :gear: CI

#48 Fix collection title property
  src/routes/api-documentation.ts
Labels: :beetle: Bug Fix

#50 Add node types
  src/routes/api-documentation.ts
  src/routes/entry-point.ts
Labels: :new: Feature

#67 Adds schema:Article to the API documentation
  src/routes/api-documentation.ts
Labels: :new: Feature

#66 Disable no-undef rule in eslint
  .eslintrc.js
Labels: :recycle: Chore

#47 Retrieve articles from repository
  src/adaptors/in-memory-articles.ts
  src/app.ts
  src/articles.ts
  src/errors/article-has-no-id.ts
  src/errors/article-not-found.ts
  src/router.ts
  src/routes/article-list.ts
  test/adaptors/in-memory-articles.test.ts
  test/errors/article-has-no-id.test.ts
  test/errors/article-not-found.test.ts
  test/router.test.ts
  test/routes/article-list.test.ts
Labels: :new: Feature
