Repository libero/article-store, pull requests merged in 2019-12, with the labels that each got.

#77 Make analyse.sh non-interactive
  .travis/analyse.sh
  Makefile
Labels: :recycle: Chore

#81 Change nodes to articles
  src/adaptors/in-memory-articles.ts
Labels: :package: Refactor

#84 Change ArticleHasNoID to ArticleHasNoId for consistency
  test/errors/article-has-no-id.test.ts
Labels: :gem: Style

#85 chore(deps-dev): upgrade hypermedia-app to 0.12.2
  .docker/docker-compose.yml
Labels: :recycle: Chore

#43 Allow creation of an article
  package-lock.json
  package.json
  src/app.ts
  src/router.ts
  src/routes/add-article.ts
  src/routes/api-documentation.ts
  src/routes/index.ts
  test/adaptors/in-memory-articles.test.ts
  test/context.ts
  test/create-article.ts
  test/routes/add-article.test.ts
Labels: :new: Feature

#83 Let MAKEFLAGS be passed through the environment
  Makefile
Labels: :hammer: Build

#86 Use `$(MAKE)` consistently
  Makefile
Labels: :recycle: Chore

#87 Turn install submake into prerequisites
  Makefile
Labels: :recycle: Chore

#80 Create the app using a factory
  src/app.ts
  src/index.ts
  test/app.test.ts
Labels: :package: Refactor

#90 Separate API documentation link middleware from the router
  src/app.ts
  src/middleware/api-documentation.ts
  test/middleware/api-documentation.test.ts
Labels: :package: Refactor

#91 Make API documentation link middleware name more explicit
  src/app.ts
  src/middleware/api-documentation-link.ts
  test/middleware/api-documentation.test.ts
Labels: :package: Refactor

#60 Use the Koa context rather than handling dependencies separately
  src/app.ts
  src/index.ts
  src/router.ts
  src/routes/add-article.ts
  src/routes/api-documentation.ts
  src/routes/article-list.ts
  src/routes/entry-point.ts
  test/app.test.ts
  test/context.ts
  test/middleware.ts
  test/router.test.ts
  test/routes/add-article.test.ts
  test/routes/api-documentation.test.ts
  test/routes/article-list.test.ts
  test/routes/entry-point.test.ts
Labels: :package: Refactor

#89 Only use id in create-article name if defined
  test/create-article.ts
  test/routes/add-article.test.ts
Labels: :package: Refactor

#74 Build with GitHub actions
  .github/workflows/ci.yml
  README.md
Labels: :gear: CI

#16 Compact JSON-LD responses
  package-lock.json
  package.json
  src/app.ts
  src/middleware/jsonld.ts
  test/middleware/jsonld.test.ts
Labels: :new: Feature

#93 Improve link to latest CI run on master
  README.md
Labels: :recycle: Chore

#92 Remove Travis CI build
  .dockerignore
  .github/analyse.sh
  .github/smoke-test.sh
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: :gear: CI

#102 Use Hydra Analyser Docker container
  .github/analyse.sh
  package-lock.json
  package.json
Labels: :recycle: Chore

#103 Prevent `if` echoing
  Makefile
Labels: :recycle: Chore

#101 Avoid using toThrow() and favour separate checks for instanceOf and message property or error
  test/adaptors/in-memory-articles.test.ts
  test/routes/add-article.test.ts
Labels: :rotating_light: Tests

#88 Check for schema:Article and schema:name in post request
  src/adaptors/in-memory-articles.ts
  src/errors/not-an-article.ts
  src/routes/add-article.ts
  test/adaptors/in-memory-articles.test.ts
  test/errors/not-an-article.test.ts
  test/routes/add-article.test.ts
Labels: :new: Feature

#111 Allow empty response bodies
  src/app.ts
  src/middleware/empty-response.ts
  test/middleware/empty-response.test.ts
Labels: :beetle: Bug Fix

#112 Use 201 Created rather than 204 No Content
  src/routes/add-article.ts
  src/routes/api-documentation.ts
  test/routes/add-article.test.ts
Labels: :new: Feature

#122 Add standard labels to prod container image
  .docker/docker-compose.prod.yml
  Dockerfile
Labels: :hammer: Build

#123 Refine CODEOWNERS to include Infrastructure Reviewers
  .github/CODEOWNERS
Labels: :recycle: Chore

#114 Article list async iterable
  package-lock.json
  package.json
  src/adaptors/in-memory-articles.ts
  src/articles.ts
  src/routes/article-list.ts
  test/adaptors/in-memory-articles.test.ts
  test/routes/add-article.test.ts
Labels: :new: Feature

#129 Remove redundant JSON-LD prefix
  src/app.ts
Labels: :beetle: Bug Fix

#128 Add operation types
  src/routes/api-documentation.ts
Labels: :new: Feature

#104 Add Hypertest scenarios
  .github/hypertest.sh
  .github/workflows/ci.yml
  test/hypertest/article.hydra
Labels: :gear: CI
