Repository libero/article-store, pull requests merged in 2020-01, with the labels that each got.

#144 Remove RDF from the Hydra link header relation type
  src/middleware/api-documentation-link.ts
Labels: :package: Refactor

#143 Change Articles.add to Articles.set
  src/adaptors/in-memory-articles.ts
  src/articles.ts
  src/errors/article-has-no-id.ts
  src/routes/add-article.ts
  src/routes/article-list.ts
  test/adaptors/in-memory-articles.test.ts
  test/errors/article-has-no-id.test.ts
  test/routes/add-article.test.ts
  test/routes/article-list.test.ts
Labels: :package: Refactor

#146 Use RDF/JS terms instead of JSON-LD strings
  package-lock.json
  package.json
  src/adaptors/in-memory-articles.ts
  src/app.ts
  src/articles.ts
  src/errors/article-not-found.ts
  src/errors/not-an-article.ts
  src/index.ts
  src/routes/add-article.ts
  src/routes/article-list.ts
  test/adaptors/in-memory-articles.test.ts
  test/app.test.ts
  test/context.ts
  test/create-article.ts
  test/errors/article-not-found.test.ts
  test/errors/not-an-article.test.ts
  test/routes/add-article.test.ts
  test/routes/article-list.test.ts
Labels: :package: Refactor

#148 Always test that the next middleware is called
  test/middleware/api-documentation.test.ts
  test/middleware/routing.test.ts
  test/routes/add-article.test.ts
Labels: :rotating_light: Tests

#147 Create data factory middleware
  src/app.ts
  src/middleware/data-factory.ts
  test/middleware/data-factory.test.ts
Labels: :package: Refactor

#151 Improve article factory options
  test/adaptors/in-memory-articles.test.ts
  test/create-article.ts
  test/routes/add-article.test.ts
  test/routes/article-list.test.ts
Labels: :package: Refactor

#152 Add named node builder
  package-lock.json
  package.json
  src/app.ts
  src/errors/not-an-article.ts
  src/namespaces.ts
  test/adaptors/in-memory-articles.test.ts
  test/create-article.ts
  test/errors/not-an-article.test.ts
  test/routes/add-article.test.ts
Labels: :package: Refactor

#160 Increase max line length to 120
  .eslintrc.js
Labels: :recycle: Chore

#158 Improve request and response typing in tests
  test/context.ts
  test/middleware.ts
Labels: :package: Refactor

#159 Improve Koa types
  src/app.ts
  src/middleware/api-documentation-link.ts
  src/middleware/data-factory.ts
  src/middleware/empty-response.ts
  src/middleware/error-handler.ts
  src/middleware/jsonld.ts
  test/app.test.ts
Labels: :package: Refactor

#161 Fix next middleware type
  test/middleware.ts
  test/middleware/api-documentation.test.ts
  test/middleware/empty-response.test.ts
  test/middleware/error-handler.test.ts
  test/middleware/jsonld.test.ts
  test/middleware/routing.test.ts
  test/routes/add-article.test.ts
  test/routes/api-documentation.test.ts
  test/routes/article-list.test.ts
  test/routes/entry-point.test.ts
Labels: :rotating_light: Tests

#157 Fix issue with services loop in wait-healthy
  .docker/docker-compose.yml
  Makefile
Labels: :hammer: Build

#115 Use RDF/JS DatasetCore
  package-lock.json
  package.json
  src/adaptors/in-memory-articles.ts
  src/app.ts
  src/articles.ts
  src/data-factory.ts
  src/errors/not-an-article.ts
  src/index.ts
  src/middleware/dataset.ts
  src/middleware/error-handler.ts
  src/middleware/jsonld.ts
  src/routes/add-article.ts
  src/routes/api-documentation.ts
  src/routes/article-list.ts
  src/routes/entry-point.ts
  test/adaptors/in-memory-articles.test.ts
  test/app.test.ts
  test/context.ts
  test/create-article.ts
  test/middleware/dataset.test.ts
  test/middleware/error-handler.test.ts
  test/middleware/jsonld.test.ts
  test/routes/add-article.test.ts
  test/routes/api-documentation.test.ts
  test/routes/article-list.test.ts
  test/routes/entry-point.test.ts
Labels: :package: Refactor

#162 Allow browsers to read the Location header
  src/app.ts
  test/app.test.ts
Labels: :beetle: Bug Fix

#164 Correct types in tests
  test/context.ts
  test/create-article.ts
  test/middleware/jsonld.test.ts
  test/router.test.ts
Labels: :package: Refactor

#165 Don't used untyped modules
  test/context.ts
  test/router.test.ts
Labels: :package: Refactor

#169 Add types for rdf-dataset-indexed
  package-lock.json
  package.json
Labels: :recycle: Chore

#166 Fix router context
  src/app.ts
  src/middleware/routing.ts
  src/router.ts
Labels: :beetle: Bug Fix

#29 chore: Added "strict" value to compiler options in tsconfig
  tsconfig.json
Labels: :recycle: Chore

#170 Only run tests in the test directory
  jest.config.js
Labels: :recycle: Chore

#171 Remove redundant try-catch
  src/routes/add-article.ts
Labels: :package: Refactor

#194 Simplify creating HTTP errors
  src/middleware/error-handler.ts
Labels: :package: Refactor

#195 Use http-status-codes library
  package-lock.json
  package.json
  src/middleware/jsonld.ts
  src/routes/add-article.ts
  src/routes/api-documentation.ts
  src/routes/article-list.ts
  src/routes/entry-point.ts
  test/app.test.ts
  test/middleware/error-handler.test.ts
  test/middleware/jsonld.test.ts
  test/middleware/routing.test.ts
  test/routes/add-article.test.ts
  test/routes/api-documentation.test.ts
  test/routes/article-list.test.ts
  test/routes/entry-point.test.ts
Labels: :package: Refactor

#196 Extract test middleware that always throws an error
  test/middleware.ts
  test/middleware/error-handler.test.ts
Labels: :package: Refactor

#200 Allow the test request to know the path
  test/context.ts
Labels: :package: Refactor

#199 Update Hypertest to 0.4.1
  .github/hypertest.sh
Labels: :recycle: Chore

#184 Uses Iri as NamedNode value and allow individual article retrieval
  src/router.ts
  src/routes/add-article.ts
  src/routes/article.ts
  src/routes/index.ts
  test/routes/add-article.test.ts
  test/routes/article.test.ts
Labels: :new: Feature

#204 Use new jest-rdf matchers
  package-lock.json
  package.json
  test/adaptors/in-memory-articles.test.ts
  test/middleware/dataset.test.ts
  test/middleware/error-handler.test.ts
  test/middleware/jsonld.test.ts
  test/routes/add-article.test.ts
  test/routes/api-documentation.test.ts
  test/routes/article-list.test.ts
  test/routes/article.test.ts
  test/routes/entry-point.test.ts
Labels: :package: Refactor

#213 Use the same data factory inside the dataset factory
  src/data-factory.ts
Labels: :package: Refactor

#214 Add data factory and dataset quad type
  src/middleware/data-factory.ts
  src/middleware/dataset.ts
Labels: :package: Refactor

#217 Fix Make exit codes
  Makefile
Labels: :hammer: Build

#116 Replacing in-memory with persistent database storage
  .docker/docker-compose.yml
  .github/workflows/ci.yml
  Makefile
  jest.config.js
  package-lock.json
  package.json
  src/adaptors/postgres-articles.ts
  src/db.ts
  src/index.ts
  src/tools/initdb.ts
  test/adaptors/postgres-articles.test.ts
Labels: :new: Feature
